### ISSUE TITLE
Delivering several times the work

### ISSUE THREAD

**Issue by llrs** [LucyMcGowan/pchallenge#1]
I found via `devtools::session_info` about this package on the p-challenge. 

I would like to know if it is possible to do several submissions of the challange. Thanks

**Comment by LucyMcGowan** [comment]
Hi @llrs! Thank you for participating! At the moment we only allow for one submission (although you are welcome to try multiple things before your final submission). If you have more questions/feedback, you can send it via our website:  http://phackathon.netlify.com/faq/
